JCN 322 Soportar el parámetro options en el método update de mongo
janis-commerce/mongodb pull request #21
Opened 2021-04-09 15:39 UTC by argenis1763

### **LINK AL TICKET**
https://fizzmod.atlassian.net/browse/JCN-321

### **DESCRIPCIÓN DEL REQUERIMIENTO**
Se requiere soportar la funcionalidad del **arrayFilters** en el método **update** del package de mongo.

Se debe agregar al método la posibilidad de recibir el parámetro **options** de mongodb para soportar todas las funcionalidades. Ver documentación: https://docs.mongodb.com/v3.6/reference/method/db.collection.updateMany/

### **DESCRIPCIÓN DE LA SOLUCIÓN**
- Se modifico el método **update** para soportar el parámetro **options**.
- Se modificaron los test.
- Se modifico el **README** y el **CHANGELOG**.

2021-04-12 13:10 UTC, gastonpereyra commented on CHANGELOG.md
> +### Added
:thinking: Para mi es un

```suggestion
### Changed
```
Ya que se esta modificando un método ya existente

2021-04-12 13:12 UTC, gastonpereyra commented on README.md
> +	items: [{ name: 'foo', price: 90 },{ name: 'bar', price: 100 }]
:question: En este ejemplo, el valor que se modificaría no sería el de `name: foo` ?

2021-04-12 13:44 UTC, gastonpereyra requested changes
Algunos comentarios chicos

2021-04-12 13:49 UTC, gastonpereyra commented on README.md
> +- options: `Object`: Optional parameters of the query [See more](https://docs.mongodb.com/v3.6/reference/method/db.collection.updateMany/#definition)
Para completar esto sumaría los links de los arrayFilters, que es talvés es la opción más interesante (por ahora)

```suggestion
- options: `Object`: Optional parameters (such as [arrayFilters](https://docs.mongodb.com/v3.6/release-notes/3.6/#arrayfilters)) of the query [See more](https://docs.mongodb.com/v3.6/reference/method/db.collection.updateMany/#definition)
```

2021-04-12 16:15 UTC, gastonpereyra approved these changes
Aprobado

2021-04-13 13:54 UTC, manuelvilche approved these changes

2021-04-14 13:00 UTC, merged