JCN-377 Corregir en metodo Save la forma de guardar ID de mongo
janis-commerce/mongodb pull request #30
Opened 2022-04-21 17:22 UTC by guillecipri

**Link al ticket:**
[Ticket](https://fizzmod.atlassian.net/browse/JCN-376) || [Subtarea](https://fizzmod.atlassian.net/browse/JCN-377)

**Requerimiento:**
Qué se espera ?
En el package de [mongodb](https://github.com/janis-commerce/mongodb) existe el método save para guardar o actualizar un registro según corresponda. Se espera que este método devuelva el id del registro que creó o actualizó.

Cuál es el problema ?
El problema esta en que cuando crea un registro nuevo no esta devolviendo el id.

Esto sucede porque el package espera sacar esta id del valor value._id, pero esto solo esta sucediendo cuando actualiza un registro y no cuando se crea.

Ejemplo
Asi devuelve el driver al usar save para crear

```
{
  lastErrorObject: {
    n: 1,
    updatedExisting: false,
    upserted: new ObjectId("62604610bcb561a692c980b6")
  },
  value: null,
  ok: 1
}
```
Asi devuelve el driver al usar save para actualizar

```
{
  lastErrorObject: {
    n: 1,
    updatedExisting: true
  },
  value: {
    _id: new ObjectId("62604610bcb561a692c980b6"),
    email: 'some-mail@fizzmod.com',
    firstname: 'Jane',
    lastname: 'Doe',
    ... resto de las propiedades
  },
  ok: 1
}
```

Acceptance criteria
Qué se necesita ?
Se requiere arreglar este comportamiento para que siempre devuelva el id. 

Para esto vamos buscarlo en

en `value._id `, como esta ahora mismo.

o en `lastErrorObject.upserted`.

Y devolverlo como _string_.

2022-04-22 12:49 UTC, moruezabal commented on lib/mongodb.js
> +			return !res.value ? res.lastErrorObject && res.lastErrorObject.upserted.toString() : res.value._id.toString();
Aquí preguntaría por la positiva de `rest.value` para dar vuelta el ternario y quede más fácil de leer.
Además, no consultaría por `res.lastErrorObject` ya que es un valor que sabemos que siempre vendrá seteado.
Quedaría algo así : `return res.value ? res.value._id.toString() : res.lastErrorObject.upserted.toString()`

2022-04-22 12:49 UTC, moruezabal commented on lib/mongodb.js
> +			return !res.value ? res.lastErrorObject && res.lastErrorObject.upserted.toString() : res.value._id.toString();
Aquí preguntaría por la positiva de `rest.value` para dar vuelta el ternario y quede más fácil de leer.
Además, no consultaría por `res.lastErrorObject` ya que es un valor que sabemos que siempre vendrá seteado.
Quedaría algo así : `return res.value ? res.value._id.toString() : res.lastErrorObject.upserted.toString()`

2022-04-22 18:20 UTC, moruezabal approved these changes
Aprobado!

2022-04-22 18:22 UTC, moruezabal approved these changes

2022-04-25 13:58 UTC, gastonpereyra commented on lib/mongodb.js
> +			return res.value ? res.value._id.toString() : res.lastErrorObject.upserted.toString();
Cuidado que tampoco es 100% seguro que `upserted` exista, asi que recomiendo

```suggestion
			return res.value ? res.value._id.toString() : res.lastErrorObject.upserted?.toString();
```

2022-04-25 14:01 UTC, gastonpereyra requested changes
Pequeño comentario

2022-04-25 17:22 UTC, gastonpereyra approved these changes

2022-05-02 12:55 UTC, merged