Jcn 394 add id struct getter
janis-commerce/mongodb pull request #32
Opened 2022-05-20 16:49 UTC by calandrajose

[Historia](https://fizzmod.atlassian.net/browse/JCAT-393)
[Subtarea](https://fizzmod.atlassian.net/browse/JCAT-394)

### Descripción del requerimiento
Se necesita agregar en el package de :leaves: [GitHub - janis-commerce/mongodb](https://github.com/janis-commerce/mongodb) alguna manera de validar el id necesario para este driver, ya que en este caso es particular, y si se quiere filtrar sin ser del tipo de dato correcto la base va a explotar y no es correcto.

Para esto se necesita crear un nuevo getter llamado idStruct, que retorne una función struct para validar objectId (que es el tipo de id que necesita mongodb).

Este nuevo getter va ser usado tanto por [GitHub - janis-commerce/model](https://github.com/janis-commerce/model) como por [GitHub - janis-commerce/api-get: A package to handle JANIS Views Get APIs](https://github.com/janis-commerce/api-get) para validar el tipo de ID antes de llegar a la base.

2022-05-20 18:21 UTC, moruezabal commented on README.md
> +await mongo.idStruct('6282c2484f64bffff55bcd7c');
Si la función es síncrona no haría falta _awaitearla_ acá ;)

2022-05-20 18:22 UTC, moruezabal commented on lib/mongodb.js
> +	get idStruct() {
Estará bueno agregarle el JSDoc a la función, ya que todas las restantes ya tienen :)

2022-05-20 18:30 UTC, moruezabal requested changes
Pequeños cambios

2022-05-23 13:40 UTC, moruezabal approved these changes

2022-05-23 21:02 UTC, gastonpereyra commented on lib/mongodb.js
> +	 * Returns a function to validate mongoDB id type
Habria que aclarar que se retorna una función

2022-05-26 18:37 UTC, gastonpereyra approved these changes

2022-05-26 18:46 UTC, merged