Jcn 445 subtarea 1 agregar filtros para get totals en mongodb
janis-commerce/mongodb pull request #37
Opened 2023-08-30 16:25 UTC by parodimatias

### Link de la historia de usuario
https://janiscommerce.atlassian.net/browse/JCN-442

### Link de la/s sub-tareas
https://janiscommerce.atlassian.net/browse/JCN-445

### Descripción del requerimiento
Se necesita modificar el package de [Mongodb](https://github.com/janis-commerce/mongodb/tree/master) para agregarle al package getTotals que acepte un campo nuevo: filters .

Este nuevo campo va a servir para los casos en los que se quiera obtener los totales de una colección en base a unos filtros, evitando hacer un get con esos filtros antes.

Este campo filters se va a tener que formatear con los helpers del package para que pueda hacer la query correctamente.

En caso que no venga este parametro, debe continuar con el comportamiento habitual
Esto va a servir para que el getTotals sepa calcular los totales segun filtros sin usarse el get con anterioridad

### Descripción de la solución
En  /lib/mongodb.js#L433  modificar el método getTotals. Agregarle filters como parametro. 
Se deberá ajustar la logica para ignorar el filter del model que haya quedado de hacer un get previo si es que este parametro existe

Se debe también parsear los filtros que vengan por parametros como se hace en el método get() en la linea 92

### Como probarlo
Ver https://github.com/janis-commerce/api-list/pull/18

2023-09-04 19:39 UTC, Alejandro-Gonzalez requested changes

2023-09-04 19:39 UTC, Alejandro-Gonzalez commented on lib/mongodb.js
> +		const parsedFilters = MongoDBFilters.parseFilters(ObjectIdHelper.ensureObjectIdsForWrite(model, filter || {}), model);
@parodimatias Acá podes dejarlo así sin el default
```
const parsedFilters = MongoDBFilters.parseFilters(ObjectIdHelper.ensureObjectIdsForWrite(model, filter), model);
```

2023-09-05 18:32 UTC, Alejandro-Gonzalez approved these changes

2023-09-05 18:49 UTC, gastonpereyra commented
Falta actualizar el README

2023-09-06 19:58 UTC, gastonpereyra approved these changes

2023-10-06 18:27 UTC, merged