Jcn-482 sumar metodo multiUpdate method
janis-commerce/mongodb pull request #40
Opened 2024-04-23 18:05 UTC by calandrajose

Link de la tarea

Epica: https://janiscommerce.atlassian.net/browse/JCN-481

Subtarea: https://janiscommerce.atlassian.net/browse/JCN-482

### Descripción del requerimiento
Actualmente nuestros paquetes de Mongo y Model no permiten realizar múltiples operaciones de actualización en una misma query a menos que exista un indice único (`multiSave`)

En este caso, en la tarea https://janiscommerce.atlassian.net/browse/JHUB-38   surge la necesidad de actualizar todos los skus de múltiples productos, lo cual hoy solo es posible de la siguiente manera:

- obteniendo todos los registros
- modificandolos desde codigo
- guardando con un multiSave

Esta misma operación podría hacerse con una sola query que contenga algo similar a esto

```
[{
	updateMany: {
		filter: { product: '123' },
		update: {
			$set: {
				brand: product1.brand
			}
		}
	}
},
{
	updateMany: {
		filter: { product: '456' },
		update: {
			$set: {
				brand: product2.brand,
				description: product2.description
			}
		}
	}
}]
```

## Solucion

Para permitir este tipo de operaciones vamos a sumar en https://www.npmjs.com/package/@janiscommerce/mongodb  el nuevo método `multiUpdate` el cual recibirá los parámetros `model` y `operations`. Este ultimo parametro sera el que se ejecutara con un bulkwrite

### Descripción de la solución | Análisis Funcional
- Se agrego el nuevo metodo parseando los filtros para que funcione igual al resto de los llamados
- Se sacan de los updates los valores que pueden generar conflictos innecesarios
- Se sumo fecha de modificacion como default

### ¿Cómo se puede probar?
Dejo pruebas realizadas en local en playground:  https://www.loom.com/share/ea24653ff8bb48899bd385439b92ca21?sid=99b91e30-3ce3-47dd-96c2-2d672f7f420a

### CHANGELOG

```
### Changed
- Add *multiUpdate* method to update multiple documents with different filters and values.
```

2024-04-23 22:30 UTC, Alejandro-Gonzalez requested changes

2024-04-23 22:30 UTC, Alejandro-Gonzalez commented on lib/mongodb.js
> +		if(!operations.length)
@calandrajose Acá te  pregunto y te consulto antes de mandarte a cambiar algo.
No deberíamos validar que tengamos `operations.data` siempre? Si es asi, validemos asi no actualizamos nada.
No deberiamos tener un `operations.filter` siempre también?  O el poder actualizar masivamente todos los registros de x collection estaría correcto en algun momento?

2024-04-25 21:06 UTC, Alejandro-Gonzalez commented on lib/mongodb.js
> +		}).filter(Boolean);
@calandrajose ese `filter(Boolean);` esta de mas

2024-04-25 21:20 UTC, Alejandro-Gonzalez approved these changes

2024-05-07 13:14 UTC, gastonpereyra commented on lib/mongodb.js
> +			await this.mongo.makeQuery(model, collection => collection
:question: Pregunta, no devuelve algun dato ? cantidad de modificados o algo asi ?

2024-05-07 18:26 UTC, calandrajose commented on lib/mongodb.js
> +			await this.mongo.makeQuery(model, collection => collection
Creo que mongo devuelve el resultado si no recuerdo mal. Queres que lo devolvamos?

2024-05-09 17:39 UTC, merged